version: '3'
services:
  payment-service:
    image: payment-service
    build: .
    ports:
      - "9090:9090"
    networks:
      - system-test_dtupay-network

networks:
  system-test_dtupay-network:
    external: true
