---
openapi: 3.0.3
info:
  title: Payment API
  version: "1.0"
paths:
  /payments:
    post:
      requestBody:
        description: "Create a payment "
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        "200":
          description: OK
components:
  schemas:
    Token:
      type: object
      properties:
        rfid:
          type: string
    Payment:
      type: object
      properties:
        amount:
          format: int32
          type: integer
        customerBankId:
          type: string
        customerId:
          type: string
        merchantBankId:
          type: string
        merchantId:
          type: string
        paymentId:
          type: string
        token:
          $ref: '#/components/schemas/Token'
        accountId:
          type: string
